//go:build !ignore_autogenerated

// This file is hand-maintained for v0.1 because the build environment does
// not yet invoke controller-gen as part of `make build`. Run `make generate`
// to regenerate after changing the types in this package.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ---------------- shared ----------------

func (in *SecretRef) DeepCopyInto(out *SecretRef) { *out = *in }
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRef) DeepCopyInto(out *ResourceRef) { *out = *in }
func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	if in.SecretRef != nil {
		out.SecretRef = in.SecretRef.DeepCopy()
	}
}
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// ---------------- RegistryBackend ----------------

func (in *AddonToggle) DeepCopyInto(out *AddonToggle) { *out = *in }
func (in *AddonToggle) DeepCopy() *AddonToggle {
	if in == nil {
		return nil
	}
	out := new(AddonToggle)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendAddons) DeepCopyInto(out *BackendAddons) {
	*out = *in
	in.Trivy.DeepCopyInto(&out.Trivy)
}
func (in *BackendAddons) DeepCopy() *BackendAddons {
	if in == nil {
		return nil
	}
	out := new(BackendAddons)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendEngineConfig) DeepCopyInto(out *BackendEngineConfig) {
	*out = *in
	in.Addons.DeepCopyInto(&out.Addons)
}
func (in *BackendEngineConfig) DeepCopy() *BackendEngineConfig {
	if in == nil {
		return nil
	}
	out := new(BackendEngineConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryBackendSpec) DeepCopyInto(out *RegistryBackendSpec) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	in.EngineConfig.DeepCopyInto(&out.EngineConfig)
}
func (in *RegistryBackendSpec) DeepCopy() *RegistryBackendSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryBackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryBackendStatus) DeepCopyInto(out *RegistryBackendStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.Endpoint != nil {
		out.Endpoint = in.Endpoint.DeepCopy()
	}
	if in.Resources != nil {
		out.Resources = make([]ResourceRef, len(in.Resources))
		copy(out.Resources, in.Resources)
	}
}
func (in *RegistryBackendStatus) DeepCopy() *RegistryBackendStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryBackendStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryBackend) DeepCopyInto(out *RegistryBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *RegistryBackend) DeepCopy() *RegistryBackend {
	if in == nil {
		return nil
	}
	out := new(RegistryBackend)
	in.DeepCopyInto(out)
	return out
}
func (in *RegistryBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RegistryBackendList) DeepCopyInto(out *RegistryBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RegistryBackend, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *RegistryBackendList) DeepCopy() *RegistryBackendList {
	if in == nil {
		return nil
	}
	out := new(RegistryBackendList)
	in.DeepCopyInto(out)
	return out
}
func (in *RegistryBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ---------------- RegistryInstance ----------------

func (in *BackendReference) DeepCopyInto(out *BackendReference) { *out = *in }
func (in *BackendReference) DeepCopy() *BackendReference {
	if in == nil {
		return nil
	}
	out := new(BackendReference)
	in.DeepCopyInto(out)
	return out
}

func (in *Retention) DeepCopyInto(out *Retention) { *out = *in }
func (in *Retention) DeepCopy() *Retention {
	if in == nil {
		return nil
	}
	out := new(Retention)
	in.DeepCopyInto(out)
	return out
}

func (in *InstanceEngineConfig) DeepCopyInto(out *InstanceEngineConfig) {
	*out = *in
	if in.Retention != nil {
		out.Retention = in.Retention.DeepCopy()
	}
}
func (in *InstanceEngineConfig) DeepCopy() *InstanceEngineConfig {
	if in == nil {
		return nil
	}
	out := new(InstanceEngineConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryInstanceSpec) DeepCopyInto(out *RegistryInstanceSpec) {
	*out = *in
	out.BackendRef = in.BackendRef
	in.EngineConfig.DeepCopyInto(&out.EngineConfig)
}
func (in *RegistryInstanceSpec) DeepCopy() *RegistryInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryInstanceStatus) DeepCopyInto(out *RegistryInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
	if in.Endpoint != nil {
		out.Endpoint = in.Endpoint.DeepCopy()
	}
	if in.Resources != nil {
		out.Resources = make([]ResourceRef, len(in.Resources))
		copy(out.Resources, in.Resources)
	}
}
func (in *RegistryInstanceStatus) DeepCopy() *RegistryInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RegistryInstance) DeepCopyInto(out *RegistryInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *RegistryInstance) DeepCopy() *RegistryInstance {
	if in == nil {
		return nil
	}
	out := new(RegistryInstance)
	in.DeepCopyInto(out)
	return out
}
func (in *RegistryInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RegistryInstanceList) DeepCopyInto(out *RegistryInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]RegistryInstance, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *RegistryInstanceList) DeepCopy() *RegistryInstanceList {
	if in == nil {
		return nil
	}
	out := new(RegistryInstanceList)
	in.DeepCopyInto(out)
	return out
}
func (in *RegistryInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
